jobs:
  verify:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Start
        uses: actions/checkout@v2
      - name: Fetch Prerequisites
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Unit Tests
        run: ./main/workflow

name: Verify

on:
  schedule:
    - cron: "55 */6 * * *"
